version: "3.9"

networks:
  dev_network:
services:
  db:
    image: postgres:latest
    ports:
      - "5431:5432"
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DB}